name: myubuntu
description: an application for ubuntu .

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  barcode_scan2: ^4.2.1
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  intl: ^0.17.0
  lottie: ^1.3.0
  path: ^1.8.1
  permission_handler: ^9.2.0
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  uuid: ^3.0.4

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
