// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVl2SCMDmpvvQV4jsApkSeGQrwF5Mwm30',
    appId: '1:258803514498:web:bd8f8256bda8b5ec66889b',
    messagingSenderId: '258803514498',
    projectId: 'my-ubuntu-2k22',
    authDomain: 'my-ubuntu-2k22.firebaseapp.com',
    storageBucket: 'my-ubuntu-2k22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ubmaUpU1wTGrcvHbrhkSQTYCe95xC0I',
    appId: '1:258803514498:android:72b33bc7f28b763a66889b',
    messagingSenderId: '258803514498',
    projectId: 'my-ubuntu-2k22',
    storageBucket: 'my-ubuntu-2k22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaLubC9KtBc5uO5RNRDOyXby7AIesf0GA',
    appId: '1:258803514498:ios:0d536d2d8363218f66889b',
    messagingSenderId: '258803514498',
    projectId: 'my-ubuntu-2k22',
    storageBucket: 'my-ubuntu-2k22.appspot.com',
    iosClientId: '258803514498-4815nfrhaob3rsg0h9kgm3apqrmmd0ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.ubun',
  );
}
